# Generated by Django 2.2.1 on 2019-06-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Bio',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
